FROM bananocoin/banano

#RUN apt-get update
#RUN apt-get install curl gzip wget -y
#
#RUN wget https://banano.steampoweredtaco.com/download/snapshot.ldb.gz -q --show-progress
#RUN gunzip snapshot.ldb.gz
#
#RUN mv snapshot.ldb /root/BananoData/data.ldb

COPY config /usr/share/nano/config
