---
version: "2.0"

services:
  web:
    image: xmconstantx/bananocraftserver
    env:
      - EULA=TRUE
      - PVP=TRUE
      - MOTD="Bananocraft Akash POC"
      - MODE=creative
      - ENABLE_COMMAND_BLOCK=true
      - ENABLE_RCON=false
      - SPAWN_PROTECTION=34
      - HARDCORE=false
      - MAX_PLAYERS=150
      - OPS=k1rby,mconstant
      - DIFFICULTY=normal
      - SERVER_NAME=BananocraftAkash
      - MEMORY=12G
      - TYPE=PAPER
      - BANANODE_IP=$BANANODE_IP
      - BANANOCRAFT_WALLET_SEED=$BANANOCRAFT_WALLET_SEED
      - WALLET_ID=$WALLET_ID
      - MASTER_WALLET=$MASTER_WALLET
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_URI=$MONGO_URI
    expose:
      - port: 25565
        protocol: tcp
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 10
        memory:
          size: 16Gi
        storage:
          size: 50Gi
  placement:
    westcoast:
      attributes:
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
