---
version: "2.0"

services:
  web:
    image: xmconstantx/bananocraftserver:01162022
    env:
      - SSH_PASSWORD=adsfsadf
      - EULA=TRUE
      - PVP=TRUE
      - MOTD="Hard Mode Survival Bananocraft Akash POC"
      - MODE=survival
      - ENABLE_COMMAND_BLOCK=true
      - ENABLE_RCON=false
      - SPAWN_PROTECTION=1
      - HARDCORE=false
      - MAX_PLAYERS=20
      - OPS=k1rby,mconstant
      - DIFFICULTY=hard
      - SERVER_NAME=SurvivalBananocraftAkash
      - MEMORY=4G
      - TYPE=PAPER
      - BANANODE_IP=asdfasdfasdfsadfadsf
      - BANANOCRAFT_WALLET_SEED=asdfasdfasdfasdfsadfsadf
      - MASTER_WALLET=asdfasdfdsafsadf
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=asdfasdfasdf
      - MONGO_URI=mongodb://root:asdfasdf@asdfasdfasdfdsafsdafadsf
    expose:
      - port: 25565
        protocol: tcp
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 6Gi
        storage:
          size: 50Gi
  placement:
    westcoast:
      attributes:
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    westcoast:
      profile: web
      count: 1
