---
version: "2.0"

services:
  web:
    image: xmconstantx/bananocraftserver
    env:
      - EULA=TRUE
      - PVP=TRUE
      - MOTD="HardCore Survival Bananocraft Akash POC"
      - MODE=survival
      - ENABLE_COMMAND_BLOCK=true
      - ENABLE_RCON=false
      - SPAWN_PROTECTION=34
      - HARDCORE=true
      - MAX_PLAYERS=20
      - OPS=asdfdsaf,asdfdsaf
      - DIFFICULTY=normal
      - SERVER_NAME=HardcoreSurvivalBananocraftAkash
      - MEMORY=4G
      - TYPE=PURPUR
      - BANANODE_IP=asdfadsf
      - BANANOCRAFT_WALLET_SEED=asdfadsfadsf
      - WALLET_ID=asdfdsafadsf
      - MASTER_WALLET=asdfadsfadsf
      - MONGO_INITDB_ROOT_USERNAME=asdfdsafa
      - MONGO_INITDB_ROOT_PASSWORD=asdfdsafasdf
      - MONGO_URI=mongodb://asfdsaf:asdfsdaf@asdfdsafdsafadsf:32672
    expose:
      - port: 25565
        protocol: tcp
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 6Gi
        storage:
          size: 5Gi
  placement:
    westcoast:
      attributes:
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    westcoast:
      profile: web
      count: 1
